export const caseMetadata = {
  beginner: { caseNumber: 'Case 01', title: 'The Locked Office', difficulty: 'Beginner', timer: '10:00', score: 500, victim: 'Professor Sarah Collins', initialNotebook: ['Professor Collins’s research papers were copied from her locked office on the evening of 15 September.', 'Nothing was forced and nothing was carried away. The door was opened with an access card.', 'Three people were in the North Wing that evening. Start with SELECT * FROM suspects;', 'Every card presented to a door is recorded. Try SELECT * FROM access_logs;', 'If a table looks long, add LIMIT 3 to see just the first few rows.'] },
  easy: { caseNumber: 'Case 02', title: 'The Dormitory Murder', difficulty: 'Easy', timer: '20:00', score: 1000, victim: 'Professor Ethan Ross', initialNotebook: ['Professor Ross was killed at 10:18 PM in North Hall Office 204.', 'The corridor lights were out from 10:13 PM to 10:23 PM. That is the window.', 'There are five suspects. Start with SELECT * FROM suspects.', 'The cameras are the fastest way to rule people out. Try cctv_logs.', 'One suspect appears nowhere during the blackout. Find them.'] },
  medium: { caseNumber: 'Case 03', title: 'The Mansion at Blackwood Hill', difficulty: 'Medium', timer: '35:00', score: 2000, victim: 'Arthur Blackwood', initialNotebook: ['Arthur Blackwood was struck once at 9:47 PM in his private study.', 'The study door is fob-controlled, but there is no camera inside the room.', 'Seven suspects. Six of them can be placed somewhere else — prove it.', 'A fob names a person, not a hand. Check the witnesses table before you trust it.', 'JOIN suspects against cctv_logs and access_logs to see who is missing.'] },
  expert: { caseNumber: 'Case 04', title: 'The Aurelian Job', difficulty: 'Expert', timer: '60:00', score: 3000, victim: 'Celia Voss', initialNotebook: ['Celia Voss was killed at 1:07 AM in Suite 7A, aboard a ship nobody left.', 'Nine suspects. Everyone was still on board when the alarm sounded.', 'Compare the Deck 7 badge times against the Deck 7 camera times for the same person.', 'If two records of the same moment disagree, one of them was changed. Find out who could change it.', 'SQLite can do the arithmetic for you: datetime(access_time, \'-12 minutes\').'] },
};

export function getCaseMetadata(difficulty) {
  return caseMetadata[difficulty] ?? null;
}
