export const cases = {
  easy: {
    difficulty: 'Easy',
    caseNumber: 'Case 01',
    title: 'The Dormitory Murder',
    timeLimit: '20 Minutes',
    concepts: ['SELECT', 'WHERE', 'ORDER BY', 'LIMIT', 'COUNT'],
    preview: 'A professor is stabbed during a ten-minute campus blackout. Five people were in the building. Four of them are on camera. Find the fifth.',
    victim: 'Professor Ethan Ross',
    date: 'October 14, 2026',
    time: '10:18 PM',
    location: 'Hawthorne University · North Hall, Office 204',
    witnesses: 'A research assistant, a lab technician, a graduate student, a security officer, and the department secretary.',
    crimeScene: 'An unlocked office with no forced entry, a wiped knife handle, and a monitor cable pulled at 10:18 PM.',
    evidence: 'Camera footage, badge records, and a fingerprint on a window that one suspect swears he never touched.',
  },
  medium: {
    difficulty: 'Medium',
    caseNumber: 'Case 02',
    title: 'The Mansion at Blackwood Hill',
    timeLimit: '35 Minutes',
    concepts: ['JOIN', 'LEFT JOIN', 'GROUP BY', 'HAVING', 'BETWEEN'],
    preview: 'Arthur Blackwood announced a new will over dinner and was dead within the hour. The study door log names his estate manager — but she was in the garage on camera at the time.',
    victim: 'Arthur Blackwood',
    date: 'November 03, 2026',
    time: '9:47 PM',
    location: 'Blackwood Estate · West Sussex',
    witnesses: 'The widow, the son, the daughter, the family solicitor, the butler, the estate manager, and the business partner.',
    crimeScene: 'A fob-controlled study with no camera inside. An open safe behind a portrait, and a mantel clock stopped at 9:47.',
    evidence: 'One page of the new will is printed on different paper. Work out who benefits from that page and you have your motive.',
  },
  expert: {
    difficulty: 'Expert',
    caseNumber: 'Case 03',
    title: 'The Aurelian Job',
    timeLimit: '60 Minutes',
    concepts: ['Multi-table JOINs', 'Subqueries', 'CTEs', 'Date arithmetic'],
    preview: 'A CEO is killed hours before she was due to name the person who stole her company\'s designs. Nine suspects, one ship, and nobody went ashore.',
    victim: 'Celia Voss',
    date: 'December 19, 2026',
    time: '1:07 AM',
    location: 'M/V Aurelian · Adriatic Sea',
    witnesses: 'Her husband, four executives, an investor, and three of the ship\'s crew.',
    crimeScene: 'A suite with no camera and no forced entry, an open safe with only one document missing, and an access panel found hanging open two decks below.',
    evidence: 'The badge log and the camera disagree about when people were on Deck 7. Only one of them was tampered with, and only three accounts could have done it.',
  },
};

export function getCase(difficulty) {
  return cases[difficulty] ?? null;
}
